package hibernate;
// Generated 23-ene-2018 8:58:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BiEnfermedades generated by hbm2java
 */
public class BiEnfermedades  implements java.io.Serializable {


     private short id;
     private String nombre;
     private Set biMascotasEnfermedadeses = new HashSet(0);

    public BiEnfermedades() {
    }

	
    public BiEnfermedades(short id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public BiEnfermedades(short id, String nombre, Set biMascotasEnfermedadeses) {
       this.id = id;
       this.nombre = nombre;
       this.biMascotasEnfermedadeses = biMascotasEnfermedadeses;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getBiMascotasEnfermedadeses() {
        return this.biMascotasEnfermedadeses;
    }
    
    public void setBiMascotasEnfermedadeses(Set biMascotasEnfermedadeses) {
        this.biMascotasEnfermedadeses = biMascotasEnfermedadeses;
    }




}


