package hibernate;
// Generated 23-ene-2018 8:58:01 by Hibernate Tools 4.3.1



/**
 * BiMascotasEnfermedadesId generated by hbm2java
 */
public class BiMascotasEnfermedadesId  implements java.io.Serializable {


     private short idenfermedad;
     private String mascota;

    public BiMascotasEnfermedadesId() {
    }

    public BiMascotasEnfermedadesId(short idenfermedad, String mascota) {
       this.idenfermedad = idenfermedad;
       this.mascota = mascota;
    }
   
    public short getIdenfermedad() {
        return this.idenfermedad;
    }
    
    public void setIdenfermedad(short idenfermedad) {
        this.idenfermedad = idenfermedad;
    }
    public String getMascota() {
        return this.mascota;
    }
    
    public void setMascota(String mascota) {
        this.mascota = mascota;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BiMascotasEnfermedadesId) ) return false;
		 BiMascotasEnfermedadesId castOther = ( BiMascotasEnfermedadesId ) other; 
         
		 return (this.getIdenfermedad()==castOther.getIdenfermedad())
 && ( (this.getMascota()==castOther.getMascota()) || ( this.getMascota()!=null && castOther.getMascota()!=null && this.getMascota().equals(castOther.getMascota()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdenfermedad();
         result = 37 * result + ( getMascota() == null ? 0 : this.getMascota().hashCode() );
         return result;
   }   


}


