package hibernate;
// Generated 23-ene-2018 8:58:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BiMascotasEnfermedades generated by hbm2java
 */
public class BiMascotasEnfermedades  implements java.io.Serializable {


     private BiMascotasEnfermedadesId id;
     private BiEnfermedades biEnfermedades;
     private BiMascotas biMascotas;
     private Date fechaInicio;
     private Date fechaCura;

    public BiMascotasEnfermedades() {
    }

	
    public BiMascotasEnfermedades(BiMascotasEnfermedadesId id, BiEnfermedades biEnfermedades, BiMascotas biMascotas, Date fechaInicio) {
        this.id = id;
        this.biEnfermedades = biEnfermedades;
        this.biMascotas = biMascotas;
        this.fechaInicio = fechaInicio;
    }
    public BiMascotasEnfermedades(BiMascotasEnfermedadesId id, BiEnfermedades biEnfermedades, BiMascotas biMascotas, Date fechaInicio, Date fechaCura) {
       this.id = id;
       this.biEnfermedades = biEnfermedades;
       this.biMascotas = biMascotas;
       this.fechaInicio = fechaInicio;
       this.fechaCura = fechaCura;
    }
   
    public BiMascotasEnfermedadesId getId() {
        return this.id;
    }
    
    public void setId(BiMascotasEnfermedadesId id) {
        this.id = id;
    }
    public BiEnfermedades getBiEnfermedades() {
        return this.biEnfermedades;
    }
    
    public void setBiEnfermedades(BiEnfermedades biEnfermedades) {
        this.biEnfermedades = biEnfermedades;
    }
    public BiMascotas getBiMascotas() {
        return this.biMascotas;
    }
    
    public void setBiMascotas(BiMascotas biMascotas) {
        this.biMascotas = biMascotas;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaCura() {
        return this.fechaCura;
    }
    
    public void setFechaCura(Date fechaCura) {
        this.fechaCura = fechaCura;
    }




}


