package hibernate;
// Generated 23-ene-2018 8:58:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BiVisitas generated by hbm2java
 */
public class BiVisitas  implements java.io.Serializable {


     private int idvisita;
     private BiMascotas biMascotas;
     private Date fecha;
     private byte temperatura;
     private int peso;

    public BiVisitas() {
    }

    public BiVisitas(int idvisita, BiMascotas biMascotas, Date fecha, byte temperatura, int peso) {
       this.idvisita = idvisita;
       this.biMascotas = biMascotas;
       this.fecha = fecha;
       this.temperatura = temperatura;
       this.peso = peso;
    }
   
    public int getIdvisita() {
        return this.idvisita;
    }
    
    public void setIdvisita(int idvisita) {
        this.idvisita = idvisita;
    }
    public BiMascotas getBiMascotas() {
        return this.biMascotas;
    }
    
    public void setBiMascotas(BiMascotas biMascotas) {
        this.biMascotas = biMascotas;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public byte getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(byte temperatura) {
        this.temperatura = temperatura;
    }
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }




}


